### ISSUE TITLE
can I download the DragGAN-Windows-GUI from outside of china?

### ISSUE THREAD

**Issue by benayat** [zhaoyun0071/DragGAN-Windows-GUI#4]
I'm a bit lost with the language barrier. is there a way to download the DragGAN-Windows-GUI from outside of China for English speakers?

**Comment by ffdown** [comment]
need different cloud for european

**Comment by sukablyadskaya** [comment]
https://drive.google.com/drive/folders/1gA3KpmT0RmvOBR_poZrGi4tnl69R8ZRc
Here you go :))

**Comment by benayat** [comment]
Downloaded and working just like the regular version!. thanks
